version: '3'
services:
  web:
    image: node:11
    working_dir: /usr/src/app
    command: sh -c "yarn && yarn dev"
    environment:
      NODE_CONFIG_ENV: docker
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8000
    depends_on:
      - db
      - cache
  db:
    image: mongo
    ports:
      - 27017
  cache:
    image: redis
    ports:
      - 6379

volumes:
  node_modules:
